---

- name: update apt cache 
  apt: update_cache=yes

- name: install apache and modules
  apt: name={{ item }} state=latest
  with_items:
    - apache2
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
  notify:
    - restart apache
  
